#ifndef HAL_STEPPER_MOTOR_HANDLER_STEPPER_CFG_H_
#define HAL_STEPPER_MOTOR_HANDLER_STEPPER_CFG_H_

#define STEPPER_PIN_1 {PORT_A,PIN_0}
#define STEPPER_PIN_2 {PORT_A,PIN_1}
#define STEPPER_PIN_3 {PORT_A,PIN_2}
#define STEPPER_PIN_4 {PORT_A,PIN_3}

#endif
